language: ruby

rvm:
  - 2.1

script:
  - bundle exec jekyll build

env:
  global:
    secure: St2cyWhtXulgKcrpxfOMWPo7ZXkH/Fk6MjDOUiUC5DmcgrUIjHU6vax66GS/EyuL9kYmAipNeRQ9DP6ohMjdcrqNGX3uhwOhvtqa0TYVJ5nAPvbXirB6y3TKA1pwNz4T3He6u7eyjYVipH2gHX9YXmTVGtEiotxplMWjAY3CoA4=

deploy:
  provider: s3
  access_key_id:
    secure: VHk/UcmWw4/OJPPEPKfRpOmSSku8dkDCHU68pHadR1EZI8cWqBu/+BXhhSJrcRzKEc9vEaKZh3ny3bSPI6dI7MJUIWaVqAG3AjjtJing8tiKaoMRlKksgkBJY4YrhkNmgu4hmi1xL6pv3OvOro5booSOngpO4MsF6zs1Z09CV1g=
  secret_access_key:
    secure: JciEdM3k7dNwRzFzlI2AtnEBCpSOumx16ttSNJC/AGDFx+w0NrSKUOuYG3+f2zV1psIf098FeFU6nvW4TXnWml6HmfyeIFz3F+qjId2wjMly7ekA8+Kq+6cYFi6+uHP5KP8+cEhDu9kBKdiWnj1XhKOkOTOeRnvY+jXBPjEWpfE=
  bucket: website-scrapy-org
  skip_cleanup: true
  local_dir: _site
  acl: public_read
  on:
    branch: master

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $DISTID --paths '/*'
