language: ruby
sudo: false
branches:
  only:
    - master

rvm:
  - 2.1

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - bundle exec jekyll build

env:
  global:
  - secure: St2cyWhtXulgKcrpxfOMWPo7ZXkH/Fk6MjDOUiUC5DmcgrUIjHU6vax66GS/EyuL9kYmAipNeRQ9DP6ohMjdcrqNGX3uhwOhvtqa0TYVJ5nAPvbXirB6y3TKA1pwNz4T3He6u7eyjYVipH2gHX9YXmTVGtEiotxplMWjAY3CoA4=
  - secure: dlVXxniVCIfNzktsvOPpZVAIAwHpDXfyp4ohhJvP+wf1g6PqCL/Cvh/9I2huuDgWdx8j4kojEWKUIqU/ppydOQqRu4+rIS6sC8WJVBtEeSE6snAFsvooZDZ/Ic+K4hLHDrWVy9nSSNEJ05cR7VoS196ehOaDZ/k+9X4RbXszCgM=
  - secure: IN7akGYJvVbjrVFFJsjXspz0QFI0bv9zYgwYTMOxauZkZAvBXuttCHLA6gvraSOeBQk/aYXFDG2mwlQOrx84o3hlGBHK5dy24gtMvPvYNEM5ApdzSvk6wUSjgzLHbBxvq+UR5Tr5ZC8pPBv4RppNslsB6vK4FDZ40PtcZyykCCo=

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: website-scrapy-org
  skip_cleanup: true
  local_dir: _site
  acl: public_read
  on:
    branch: master

after_deploy:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $DISTID --paths '/*'
