# Site settings
title: Scrapy - A Fast and Powerful Scraping and Web Crawling Framework
url: "https://scrapy.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8

navigation:
- text: Download
  url: download/
- text: Documentation
  url: doc/
- text: Community
  url: community/
- text: Companies
  url: companies/
- text: Commercial Support
  url: support/
